### ISSUE TITLE
Add Workflow tutorial

### ISSUE THREAD

**Issue by baimafeima** [solus-project/help-center-docs#58]
Each desktop environment follows different design principles and these in turn accomodate different workflows. A workflow guide for each desktop environment could explain its central components, what default keyboard shortcuts help to navigate it and how the desktop environment is intended to be used for getting things done.

**Comment by JoshStrobl** [comment]
I think this would be best left to the respective projects to present their own documentation on it (such as [GNOME](https://help.gnome.org/users/)), with Budgie being the exception since we already provide Budgie documentation, which can always be expanded on in the future. Furthermore, we have various sections for configuration, which cover all the desktop environments we offer.
